#!/usr/bin/env bash
# =============================================================================
# PowerKit Defaults Configuration - KISS/DRY Version
# =============================================================================
# All default values for PowerKit. Users override via tmux.conf options.
# shellcheck disable=SC2034

# Source guard
[[ -n "${_POWERKIT_DEFAULTS_LOADED:-}" ]] && return 0
_POWERKIT_DEFAULTS_LOADED=1

# =============================================================================
# BASE DEFAULTS (DRY - reused across plugins)
# =============================================================================
#
# Default cache directory name
_DEFAULT_CACHE_DIRECTORY=tmux-powerkit

# Default colors for all plugins (semantic names)
_DEFAULT_ACCENT="secondary"
_DEFAULT_ACCENT_ICON="active"
_DEFAULT_WARNING="warning"
_DEFAULT_WARNING_ICON="warning-strong"
_DEFAULT_CRITICAL="error"
_DEFAULT_CRITICAL_ICON="error-strong"

# Default thresholds
_DEFAULT_WARNING_THRESHOLD="70"
_DEFAULT_CRITICAL_THRESHOLD="90"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

# Get plugin default value by name
# Usage: get_powerkit_plugin_default "battery" "icon"
get_powerkit_plugin_default() {
    local var_name="POWERKIT_PLUGIN_${1^^}_${2^^}"
    var_name="${var_name//-/_}"
    printf '%s' "${!var_name:-}"
}
get_plugin_default() { get_powerkit_plugin_default "$@"; }

# =============================================================================
# CORE OPTIONS
# =============================================================================

POWERKIT_DEFAULT_THEME="tokyo-night"
POWERKIT_DEFAULT_THEME_VARIANT="night"
POWERKIT_DEFAULT_DISABLE_PLUGINS=0
POWERKIT_DEFAULT_BAR_LAYOUT="single"
POWERKIT_DEFAULT_TRANSPARENT="false"
POWERKIT_DEFAULT_PLUGINS="datetime,hostname,git,battery,cpu,memory"
POWERKIT_DEFAULT_STATUS_LEFT_LENGTH="100"
POWERKIT_DEFAULT_STATUS_RIGHT_LENGTH="1000"
POWERKIT_DEFAULT_STATUS_INTERVAL="5"

# =============================================================================
# SEPARATORS
# Left separator (status-left/windows): right-facing (→)
# Right separator (status-right/plugins): left-facing (←)
# Style: "rounded" (pill effect) or "normal" (powerline arrows)
# =============================================================================

POWERKIT_DEFAULT_SEPARATOR_STYLE="rounded"

POWERKIT_DEFAULT_LEFT_SEPARATOR=$'\ue0b0'
POWERKIT_DEFAULT_RIGHT_SEPARATOR=$'\ue0b2'
POWERKIT_DEFAULT_LEFT_SEPARATOR_INVERSE=$'\ue0b1'
POWERKIT_DEFAULT_RIGHT_SEPARATOR_INVERSE=$'\ue0b3'
POWERKIT_DEFAULT_LEFT_SEPARATOR_ROUNDED=$'\ue0b6'
POWERKIT_DEFAULT_RIGHT_SEPARATOR_ROUNDED=$'\ue0b4'

# =============================================================================
# SESSION & WINDOW
# =============================================================================

POWERKIT_DEFAULT_SESSION_ICON="auto"
POWERKIT_DEFAULT_ACTIVE_WINDOW_ICON=$'\ue795'
POWERKIT_DEFAULT_INACTIVE_WINDOW_ICON=$'\uf489'
POWERKIT_DEFAULT_ZOOMED_WINDOW_ICON=$'\uf531'
POWERKIT_DEFAULT_PANE_SYNCHRONIZED_ICON="✵"
POWERKIT_DEFAULT_ACTIVE_WINDOW_TITLE="#W "
POWERKIT_DEFAULT_INACTIVE_WINDOW_TITLE="#W "
POWERKIT_DEFAULT_WINDOW_WITH_ACTIVITY_STYLE="italics"
POWERKIT_DEFAULT_ACTIVE_WINDOW_NUMBER_BG="accent"
POWERKIT_DEFAULT_INACTIVE_WINDOW_NUMBER_BG="border-subtle"
POWERKIT_DEFAULT_INACTIVE_WINDOW_CONTENT_BG="border"
POWERKIT_DEFAULT_ACTIVE_PANE_BORDER_STYLE="border-strong"
POWERKIT_DEFAULT_INACTIVE_PANE_BORDER_STYLE="surface"
POWERKIT_DEFAULT_ACTIVE_WINDOW_CONTENT_BG="primary"
POWERKIT_DEFAULT_STATUS_BELL_STYLE="bold"

# =============================================================================
# HELPER KEYBINDINGS
# =============================================================================

POWERKIT_DEFAULT_HELPER_KEY="?"
POWERKIT_DEFAULT_HELPER_WIDTH="80%"
POWERKIT_DEFAULT_HELPER_HEIGHT="80%"
POWERKIT_DEFAULT_OPTIONS_KEY="?"
POWERKIT_DEFAULT_OPTIONS_WIDTH="80%"
POWERKIT_DEFAULT_OPTIONS_HEIGHT="80%"
POWERKIT_DEFAULT_KEYBINDINGS_KEY="B"
POWERKIT_DEFAULT_KEYBINDINGS_WIDTH="80%"
POWERKIT_DEFAULT_KEYBINDINGS_HEIGHT="80%"

# =============================================================================
# PLUGINS
# =============================================================================

# --- audiodevices ---
POWERKIT_PLUGIN_AUDIODEVICES_ICON=$'\uf025'
POWERKIT_PLUGIN_AUDIODEVICES_INPUT_ICON=$'\uf130'
POWERKIT_PLUGIN_AUDIODEVICES_OUTPUT_ICON=$'\uf028'
POWERKIT_PLUGIN_AUDIODEVICES_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_AUDIODEVICES_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_AUDIODEVICES_SHOW="both"
POWERKIT_PLUGIN_AUDIODEVICES_SEPARATOR=" | "
POWERKIT_PLUGIN_AUDIODEVICES_CACHE_TTL="15"
POWERKIT_PLUGIN_AUDIODEVICES_MAX_LENGTH="15"
POWERKIT_PLUGIN_AUDIODEVICES_INPUT_KEY="P"
POWERKIT_PLUGIN_AUDIODEVICES_OUTPUT_KEY="O"

# --- battery ---
POWERKIT_PLUGIN_BATTERY_ICON="󰁹"
POWERKIT_PLUGIN_BATTERY_ICON_LOW="󰂃"
POWERKIT_PLUGIN_BATTERY_ICON_CHARGING="󰂄"
POWERKIT_PLUGIN_BATTERY_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_BATTERY_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_BATTERY_CACHE_TTL="60"
POWERKIT_PLUGIN_BATTERY_DISPLAY_MODE="percentage"
POWERKIT_PLUGIN_BATTERY_LOW_THRESHOLD="30"
POWERKIT_PLUGIN_BATTERY_LOW_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_BATTERY_LOW_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_BATTERY_WARNING_THRESHOLD="50"
POWERKIT_PLUGIN_BATTERY_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_BATTERY_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"

# --- bluetooth ---
POWERKIT_PLUGIN_BLUETOOTH_ICON="󰂯"
POWERKIT_PLUGIN_BLUETOOTH_ICON_OFF="󰂲"
POWERKIT_PLUGIN_BLUETOOTH_ICON_CONNECTED="󰂱"
POWERKIT_PLUGIN_BLUETOOTH_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_BLUETOOTH_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_BLUETOOTH_OFF_ACCENT_COLOR="disabled"
POWERKIT_PLUGIN_BLUETOOTH_OFF_ACCENT_COLOR_ICON="disabled"
POWERKIT_PLUGIN_BLUETOOTH_CONNECTED_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_BLUETOOTH_CONNECTED_ACCENT_COLOR_ICON="success"
POWERKIT_PLUGIN_BLUETOOTH_SHOW_DEVICE="true"
POWERKIT_PLUGIN_BLUETOOTH_SHOW_BATTERY="true"
POWERKIT_PLUGIN_BLUETOOTH_FORMAT="all"
POWERKIT_PLUGIN_BLUETOOTH_MAX_LENGTH="25"
POWERKIT_PLUGIN_BLUETOOTH_CACHE_TTL="30"

# --- brightness ---
POWERKIT_PLUGIN_BRIGHTNESS_ICON="󰤞"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_LOW="󰤚"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_MEDIUM="󰤝"
POWERKIT_PLUGIN_BRIGHTNESS_ICON_HIGH="󰤞"
POWERKIT_PLUGIN_BRIGHTNESS_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_BRIGHTNESS_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_BRIGHTNESS_CACHE_TTL="10"

# --- camera ---
POWERKIT_PLUGIN_CAMERA_ICON=$'\uf030'
POWERKIT_PLUGIN_CAMERA_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_CAMERA_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_CAMERA_ACTIVE_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_CAMERA_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_CAMERA_SHOW="on"
POWERKIT_PLUGIN_CAMERA_CACHE_TTL="2"
POWERKIT_PLUGIN_CAMERA_SHOW_WHEN_INACTIVE="false"

# --- cloud ---
POWERKIT_PLUGIN_CLOUD_ICON=$'\uf0c2'
POWERKIT_PLUGIN_CLOUD_ICON_AWS=$'\ue7ad'
POWERKIT_PLUGIN_CLOUD_ICON_GCP=$'\ue7f1'
POWERKIT_PLUGIN_CLOUD_ICON_AZURE=$'\ue754'
POWERKIT_PLUGIN_CLOUD_ICON_MULTI="☁️"
POWERKIT_PLUGIN_CLOUD_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_CLOUD_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_CLOUD_PROD_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_CLOUD_PROVIDERS="all"
POWERKIT_PLUGIN_CLOUD_FORMAT="short"
POWERKIT_PLUGIN_CLOUD_SHOW_ACCOUNT="false"
POWERKIT_PLUGIN_CLOUD_SHOW_REGION="true"
POWERKIT_PLUGIN_CLOUD_MAX_LENGTH="40"
POWERKIT_PLUGIN_CLOUD_SEPARATOR=" | "
POWERKIT_PLUGIN_CLOUD_WARN_ON_PROD="true"
POWERKIT_PLUGIN_CLOUD_PROD_KEYWORDS="prod,production,prd"
POWERKIT_PLUGIN_CLOUD_CACHE_TTL="120"

# --- cloudstatus ---
POWERKIT_PLUGIN_CLOUDSTATUS_ICON="☁️"
POWERKIT_PLUGIN_CLOUDSTATUS_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_CLOUDSTATUS_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_CLOUDSTATUS_PROVIDERS="aws,azure,gcp,cloudflare"
POWERKIT_PLUGIN_CLOUDSTATUS_FORMAT="icon_symbol"  # "icon_symbol", "name_symbol", "icon_only", "name_only"
POWERKIT_PLUGIN_CLOUDSTATUS_SEPARATOR="|"
POWERKIT_PLUGIN_CLOUDSTATUS_SYMBOLS="simple"  # "simple" or "emoji"
POWERKIT_PLUGIN_CLOUDSTATUS_TIMEOUT="5"
POWERKIT_PLUGIN_CLOUDSTATUS_CACHE_TTL="7200"  # 2 hours
POWERKIT_PLUGIN_CLOUDSTATUS_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_CLOUDSTATUS_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_CLOUDSTATUS_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_CLOUDSTATUS_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_CLOUDSTATUS_ISSUES_ONLY="true"  # Only show providers with issues/outages
POWERKIT_PLUGIN_CLOUDSTATUS_WARNING_THRESHOLD="0"  # Minimum severity: 0=show all, 1=minor+, 2=major+, 3=critical only
POWERKIT_PLUGIN_CLOUDSTATUS_CRITICAL_THRESHOLD="0"  # Critical severity threshold for different styling

# --- cpu ---
POWERKIT_PLUGIN_CPU_ICON=$'\uf4bc'
POWERKIT_PLUGIN_CPU_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_CPU_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_CPU_CACHE_TTL="5"
POWERKIT_PLUGIN_CPU_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_CPU_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"
POWERKIT_PLUGIN_CPU_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_CPU_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_CPU_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_CPU_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- gpu ---
POWERKIT_PLUGIN_GPU_ICON=$'\uf1b2'
POWERKIT_PLUGIN_GPU_ICON_NVIDIA=$'\uf110d'
POWERKIT_PLUGIN_GPU_ICON_AMD=$'\uf2db'
POWERKIT_PLUGIN_GPU_ICON_INTEL=$'\ue73d'
POWERKIT_PLUGIN_GPU_ICON_APPLE=$'\uf179'
POWERKIT_PLUGIN_GPU_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_GPU_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_GPU_SHOW_MEMORY="true"
POWERKIT_PLUGIN_GPU_CACHE_TTL="5"
POWERKIT_PLUGIN_GPU_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_GPU_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"
POWERKIT_PLUGIN_GPU_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_GPU_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_GPU_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_GPU_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- datetime ---
POWERKIT_PLUGIN_DATETIME_ICON=$'\uf073'
POWERKIT_PLUGIN_DATETIME_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_DATETIME_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_DATETIME_FORMAT="datetime"
POWERKIT_PLUGIN_DATETIME_TIMEZONE=""
POWERKIT_PLUGIN_DATETIME_SHOW_WEEK="false"
POWERKIT_PLUGIN_DATETIME_SEPARATOR=" "

# --- disk ---
POWERKIT_PLUGIN_DISK_ICON=$'\uf0a0'
POWERKIT_PLUGIN_DISK_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_DISK_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_DISK_MOUNT="/"
POWERKIT_PLUGIN_DISK_FORMAT="percent"
POWERKIT_PLUGIN_DISK_CACHE_TTL="120"
POWERKIT_PLUGIN_DISK_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_DISK_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"
POWERKIT_PLUGIN_DISK_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_DISK_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_DISK_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_DISK_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL"

# --- external_ip ---
POWERKIT_PLUGIN_EXTERNAL_IP_ICON="󰩟"
POWERKIT_PLUGIN_EXTERNAL_IP_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_EXTERNAL_IP_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_EXTERNAL_IP_CACHE_TTL="600"

# --- git ---
POWERKIT_PLUGIN_GIT_ICON=$'\uf1d2'
POWERKIT_PLUGIN_GIT_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_GIT_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_GIT_CACHE_TTL="10"
POWERKIT_PLUGIN_GIT_MODIFIED_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_GIT_MODIFIED_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"

# --- hostname ---
POWERKIT_PLUGIN_HOSTNAME_ICON="󰍹"
POWERKIT_PLUGIN_HOSTNAME_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_HOSTNAME_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_HOSTNAME_FORMAT="short"

# --- kubernetes ---
POWERKIT_PLUGIN_KUBERNETES_ICON=$'\ue81d'
POWERKIT_PLUGIN_KUBERNETES_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_KUBERNETES_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_KUBERNETES_DISPLAY_MODE="connected"
POWERKIT_PLUGIN_KUBERNETES_SHOW_NAMESPACE="false"
POWERKIT_PLUGIN_KUBERNETES_CONNECTIVITY_TIMEOUT="2"
POWERKIT_PLUGIN_KUBERNETES_CONNECTIVITY_CACHE_TTL="120"
POWERKIT_PLUGIN_KUBERNETES_CACHE_TTL="60"
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_KEY="K"
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_WIDTH="50%"
POWERKIT_PLUGIN_KUBERNETES_CONTEXT_SELECTOR_HEIGHT="50%"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_KEY="N"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_WIDTH="50%"
POWERKIT_PLUGIN_KUBERNETES_NAMESPACE_SELECTOR_HEIGHT="50%"

# --- loadavg ---
POWERKIT_PLUGIN_LOADAVG_ICON="󱦟"
POWERKIT_PLUGIN_LOADAVG_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_LOADAVG_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_LOADAVG_FORMAT="1"
POWERKIT_PLUGIN_LOADAVG_CACHE_TTL="10"
POWERKIT_PLUGIN_LOADAVG_WARNING_THRESHOLD_MULTIPLIER="2"
POWERKIT_PLUGIN_LOADAVG_CRITICAL_THRESHOLD_MULTIPLIER="4"
POWERKIT_PLUGIN_LOADAVG_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_LOADAVG_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_LOADAVG_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_LOADAVG_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL"

# --- memory ---
POWERKIT_PLUGIN_MEMORY_ICON=$'\uefc5'
POWERKIT_PLUGIN_MEMORY_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_MEMORY_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_MEMORY_FORMAT="percent"
POWERKIT_PLUGIN_MEMORY_CACHE_TTL="5"
POWERKIT_PLUGIN_MEMORY_WARNING_THRESHOLD="$_DEFAULT_WARNING_THRESHOLD"
POWERKIT_PLUGIN_MEMORY_CRITICAL_THRESHOLD="$_DEFAULT_CRITICAL_THRESHOLD"
POWERKIT_PLUGIN_MEMORY_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_MEMORY_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_MEMORY_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_MEMORY_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- microphone ---
POWERKIT_PLUGIN_MICROPHONE_ICON=$'\ued03'
POWERKIT_PLUGIN_MICROPHONE_MUTED_ICON=$'\uefc6'
POWERKIT_PLUGIN_MICROPHONE_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_MICROPHONE_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_MICROPHONE_CACHE_TTL="2"
POWERKIT_PLUGIN_MICROPHONE_ACTIVE_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_MICROPHONE_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_MICROPHONE_MUTED_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_MICROPHONE_MUTED_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"

# --- network ---
POWERKIT_PLUGIN_NETWORK_ICON="󰛳"
POWERKIT_PLUGIN_NETWORK_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_NETWORK_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_NETWORK_INTERFACE=""
POWERKIT_PLUGIN_NETWORK_CACHE_TTL="5"
POWERKIT_PLUGIN_NETWORK_THRESHOLD="0"

# --- nowplaying ---
POWERKIT_PLUGIN_NOWPLAYING_ICON="󰝚"
POWERKIT_PLUGIN_NOWPLAYING_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_NOWPLAYING_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_NOWPLAYING_FORMAT="%artist% - %track%"
POWERKIT_PLUGIN_NOWPLAYING_MAX_LENGTH="40"
POWERKIT_PLUGIN_NOWPLAYING_NOT_PLAYING=""
POWERKIT_PLUGIN_NOWPLAYING_BACKEND="auto"
POWERKIT_PLUGIN_NOWPLAYING_IGNORE_PLAYERS="IGNORE"
POWERKIT_PLUGIN_NOWPLAYING_CACHE_TTL="5"

# --- packages ---
POWERKIT_PLUGIN_PACKAGES_ICON=$'\ueb29'
POWERKIT_PLUGIN_PACKAGES_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_PACKAGES_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_PACKAGES_BACKEND="auto"
POWERKIT_PLUGIN_PACKAGES_BREW_OPTIONS="--greedy"
POWERKIT_PLUGIN_PACKAGES_CACHE_TTL="3600"

# --- smartkey ---
POWERKIT_PLUGIN_SMARTKEY_ICON=$'\uf084'
POWERKIT_PLUGIN_SMARTKEY_WAITING_ICON=$'\ue23f'
POWERKIT_PLUGIN_SMARTKEY_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_SMARTKEY_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_SMARTKEY_WAITING_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_SMARTKEY_WAITING_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_SMARTKEY_CACHE_TTL="2"
POWERKIT_PLUGIN_SMARTKEY_SHOW_WHEN_INACTIVE="false"

# --- temperature ---
POWERKIT_PLUGIN_TEMPERATURE_ICON=$'\uf2c7'
POWERKIT_PLUGIN_TEMPERATURE_ICON_HOT=$'\uf2c7'
POWERKIT_PLUGIN_TEMPERATURE_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_TEMPERATURE_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_TEMPERATURE_UNIT="C"
POWERKIT_PLUGIN_TEMPERATURE_SOURCE="cpu"
POWERKIT_PLUGIN_TEMPERATURE_CACHE_TTL="10"
POWERKIT_PLUGIN_TEMPERATURE_WARNING_THRESHOLD="60"
POWERKIT_PLUGIN_TEMPERATURE_CRITICAL_THRESHOLD="80"
POWERKIT_PLUGIN_TEMPERATURE_HIDE_BELOW_THRESHOLD="" # Empty=show always, or set temp value (e.g. "50")
POWERKIT_PLUGIN_TEMPERATURE_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_TEMPERATURE_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_TEMPERATURE_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_TEMPERATURE_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- uptime ---
POWERKIT_PLUGIN_UPTIME_ICON=$'\ue382'
POWERKIT_PLUGIN_UPTIME_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_UPTIME_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_UPTIME_CACHE_TTL="300"

# --- volume ---
POWERKIT_PLUGIN_VOLUME_ICON=$'\uf028'
POWERKIT_PLUGIN_VOLUME_ICON_MUTED=$'\ueee8'
POWERKIT_PLUGIN_VOLUME_ICON_LOW=$'\uf027'
POWERKIT_PLUGIN_VOLUME_ICON_MEDIUM=$'\uf028'
POWERKIT_PLUGIN_VOLUME_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_VOLUME_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_VOLUME_MUTED_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_VOLUME_MUTED_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_VOLUME_LOW_THRESHOLD="30"
POWERKIT_PLUGIN_VOLUME_MEDIUM_THRESHOLD="70"
POWERKIT_PLUGIN_VOLUME_CACHE_TTL="5"

# --- vpn ---
POWERKIT_PLUGIN_VPN_ICON=$'\ue672'
POWERKIT_PLUGIN_VPN_ICON_DISCONNECTED="󰫞"
POWERKIT_PLUGIN_VPN_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_VPN_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_VPN_SHOW_NAME="true"
POWERKIT_PLUGIN_VPN_SHOW_IP="false"
POWERKIT_PLUGIN_VPN_SHOW_WHEN_DISCONNECTED="false"
POWERKIT_PLUGIN_VPN_MAX_LENGTH="20"
POWERKIT_PLUGIN_VPN_CACHE_TTL="30"

# --- weather ---
POWERKIT_PLUGIN_WEATHER_ICON=$'\uf0c2'
POWERKIT_PLUGIN_WEATHER_ICON_MODE="static"
POWERKIT_PLUGIN_WEATHER_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_WEATHER_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_WEATHER_LOCATION=""
POWERKIT_PLUGIN_WEATHER_UNIT=""
POWERKIT_PLUGIN_WEATHER_FORMAT="minimal"
POWERKIT_PLUGIN_WEATHER_CACHE_TTL="900"

# --- wifi ---
POWERKIT_PLUGIN_WIFI_ICON="󰤨"
POWERKIT_PLUGIN_WIFI_ICON_DISCONNECTED="󰤭"
POWERKIT_PLUGIN_WIFI_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_WIFI_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_WIFI_DISCONNECTED_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_WIFI_DISCONNECTED_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_WIFI_SHOW_SSID="true"
POWERKIT_PLUGIN_WIFI_SHOW_IP="false"
POWERKIT_PLUGIN_WIFI_SHOW_SIGNAL="false"
POWERKIT_PLUGIN_WIFI_HIDE_WHEN_CONNECTED="false"
POWERKIT_PLUGIN_WIFI_CACHE_TTL="30"

# --- ping ---
POWERKIT_PLUGIN_PING_ICON=$'\uf012'
POWERKIT_PLUGIN_PING_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_PING_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_PING_HOST="8.8.8.8"
POWERKIT_PLUGIN_PING_COUNT="1"
POWERKIT_PLUGIN_PING_TIMEOUT="2"
POWERKIT_PLUGIN_PING_UNIT="ms"
POWERKIT_PLUGIN_PING_CACHE_TTL="15"
POWERKIT_PLUGIN_PING_WARNING_THRESHOLD="100"
POWERKIT_PLUGIN_PING_CRITICAL_THRESHOLD="300"
POWERKIT_PLUGIN_PING_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_PING_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_PING_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_PING_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- ssh ---
POWERKIT_PLUGIN_SSH_ICON=$'\uf489'
POWERKIT_PLUGIN_SSH_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_SSH_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_SSH_ACTIVE_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_SSH_ACTIVE_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_SSH_FORMAT="auto"
POWERKIT_PLUGIN_SSH_TEXT="SSH"
POWERKIT_PLUGIN_SSH_SHOW_WHEN_LOCAL="false"
POWERKIT_PLUGIN_SSH_DETECTION_MODE="current"  # "session", "current" (focused pane), or "any" (all panes)

# --- fan ---
POWERKIT_PLUGIN_FAN_ICON=$'\uefa7'
POWERKIT_PLUGIN_FAN_ICON_FAST=$'\uf421'
POWERKIT_PLUGIN_FAN_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_FAN_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_FAN_SOURCE="auto"
POWERKIT_PLUGIN_FAN_FORMAT="raw"
POWERKIT_PLUGIN_FAN_CACHE_TTL="10"
POWERKIT_PLUGIN_FAN_HIDE_WHEN_IDLE="false"
POWERKIT_PLUGIN_FAN_SELECTION="active"  # "auto" (first), "all", "active", or specific fans like "1,2,6"
POWERKIT_PLUGIN_FAN_SEPARATOR=" | "  # Separator when showing multiple fans
POWERKIT_PLUGIN_FAN_WARNING_THRESHOLD="3000"
POWERKIT_PLUGIN_FAN_CRITICAL_THRESHOLD="5000"
POWERKIT_PLUGIN_FAN_WARNING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_FAN_WARNING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_FAN_CRITICAL_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_FAN_CRITICAL_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"

# --- timezones ---
POWERKIT_PLUGIN_TIMEZONES_ICON=$'\uf0ac'
POWERKIT_PLUGIN_TIMEZONES_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_TIMEZONES_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_TIMEZONES_ZONES=""
POWERKIT_PLUGIN_TIMEZONES_FORMAT="%H:%M"
POWERKIT_PLUGIN_TIMEZONES_SEPARATOR=" | "
POWERKIT_PLUGIN_TIMEZONES_SHOW_LABEL="true"

# --- terraform ---
POWERKIT_PLUGIN_TERRAFORM_ICON=$'\ue69a'
POWERKIT_PLUGIN_TERRAFORM_ICON_TOFU=$'\ue69a'
POWERKIT_PLUGIN_TERRAFORM_ACCENT_COLOR="$_DEFAULT_ACCENT"
POWERKIT_PLUGIN_TERRAFORM_ACCENT_COLOR_ICON="$_DEFAULT_ACCENT_ICON"
POWERKIT_PLUGIN_TERRAFORM_TOOL="terraform"
POWERKIT_PLUGIN_TERRAFORM_SHOW_ONLY_IN_DIR="true"
POWERKIT_PLUGIN_TERRAFORM_SHOW_PENDING="true"
POWERKIT_PLUGIN_TERRAFORM_WARN_ON_PROD="true"
POWERKIT_PLUGIN_TERRAFORM_PROD_KEYWORDS="prod,production,prd"
POWERKIT_PLUGIN_TERRAFORM_PROD_ACCENT_COLOR="$_DEFAULT_CRITICAL"
POWERKIT_PLUGIN_TERRAFORM_PROD_ACCENT_COLOR_ICON="$_DEFAULT_CRITICAL_ICON"
POWERKIT_PLUGIN_TERRAFORM_PENDING_ACCENT_COLOR="$_DEFAULT_WARNING"
POWERKIT_PLUGIN_TERRAFORM_PENDING_ACCENT_COLOR_ICON="$_DEFAULT_WARNING_ICON"
POWERKIT_PLUGIN_TERRAFORM_WORKSPACE_KEY="W"
POWERKIT_PLUGIN_TERRAFORM_CACHE_TTL="30"

# =============================================================================
# SYSTEM CONSTANTS
# =============================================================================

# Byte sizes (used by disk, network plugins)
POWERKIT_BYTE_KB=1024
POWERKIT_BYTE_MB=1048576
POWERKIT_BYTE_GB=1073741824
POWERKIT_BYTE_TB=1099511627776

# Cache
POWERKIT_PLUGIN_CACHE_CLEAR_KEY="Q"

# Timing
POWERKIT_TIMING_CPU_SAMPLE="0.1"
POWERKIT_TIMING_CACHE_INTERFACE="300"
POWERKIT_TIMING_CACHE_LONG="3600"
POWERKIT_TIMING_MIN_DELTA="0.1"
POWERKIT_TIMING_FALLBACK="1"

# Performance limits
POWERKIT_PERF_CPU_PROCESS_LIMIT="50"
POWERKIT_PERF_OPTIONS_PLUGIN_LIMIT="30"

# iostat
POWERKIT_IOSTAT_COUNT="2"
POWERKIT_IOSTAT_CPU_FIELD="6"
POWERKIT_IOSTAT_BASELINE="100"

# Load average multipliers
POWERKIT_LOADAVG_WARNING_MULTIPLIER="2.0"
POWERKIT_LOADAVG_CRITICAL_MULTIPLIER="4.0"

# Formatting
POWERKIT_FORMAT_OPTION_WIDTH="50"
POWERKIT_FORMAT_KEY_WIDTH="15"
POWERKIT_LIMIT_KEYBINDINGS_ROOT="20"

# Fallback
POWERKIT_FALLBACK_STATUS_BG="#292e42"
POWERKIT_BG_DEFAULT="default"

# ANSI colors (for terminal helpers)
POWERKIT_ANSI_BOLD='\033[1m'
POWERKIT_ANSI_DIM='\033[2m'
POWERKIT_ANSI_RESET='\033[0m'
POWERKIT_ANSI_RED='\033[31m'
POWERKIT_ANSI_GREEN='\033[32m'
POWERKIT_ANSI_YELLOW='\033[33m'
POWERKIT_ANSI_BLUE='\033[34m'
POWERKIT_ANSI_MAGENTA='\033[35m'
POWERKIT_ANSI_CYAN='\033[36m'
